include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - linux/**

linter:
  rules:
    # Imports grouped and sorted the same way in every file.
    directives_ordering: true
